---
title: "anime tidytuesday"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tidy_anime <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-23/tidy_anime.csv")

library(tidyverse)
```

```{r}
View(tidy_anime)
```


```{r}
tidy_anime %>%   
  select(animeID, name, popularity, rank, score, favorites, members)
```



Quels sont les 20 meilleurs animés japonnais?

```{r}
anime_scores <- tidy_anime %>% 
  select(animeID, name, popularity, rank, score, scored_by, favorites, members) %>% 
  distinct()
  
anime_scores %>% 
  arrange(rank) %>% 
  slice(1:20) %>% 
  ggplot(aes(reorder(name, score), score, colour = name)) + 
  geom_point(show.legend = F) + 
  coord_flip() +
  labs(title = "Top 20 Anime en note ",
       x = "",
       y = "Score de 1 à 10",
       caption = "@axelsamax -- Sept 2019")
       
```


Quel animé est le plus populaire?
```{r}
anime_scores %>%
  arrange(popularity) %>%
  slice(1:20) %>%  
  distinct() %>% 
  ggplot(aes(reorder(name, -popularity), members, fill = name)) +
  geom_col(show.legend = F) +
  coord_flip() +
  labs(title = "Top 20 Anime par popularité", 
       x = "", 
       y = "nombre de fans")
  
```

```{r}
anime_scores %>% 
  filter(popularity <= 50) %>%
  ggplot(aes(score, scored_by, colour = name)) + 
  geom_point() + 
  geom_text(aes(label = name, ), check_overlap = T, show.legend = F, size = 3, hjust = 1) + 
  xlim(c(6, 10)) +
  labs(title = "Est ce que popularité siginifie qualité", 
       subtitle = "Top 50 anime basé sur la popularité",
       y = "Nombre de fans",
       x = "Score de 1 à 10)") + 
  theme(legend.position = 'none')
```


```{r}
df %>%
  select(name, type, source,episodes, rating,
         scored_by, rank, popularity, members, favorites) %>%
  
  ### Extract unique elements  
  unique() %>%
  
  ### Arrange in descending order and select the first 10 elements
  arrange(desc(episodes)) %>% 
  head(10) %>%
  
    ### Plot
    ggplot(aes(x=reorder(name, episodes), y = episodes, fill = name)) +
    geom_col() +
    coord_flip() +
    labs(title = "Quelles est l'animé avec le plus grand nombre d'épisode",
         subtitle = "Top 10", 
         x = "", 
         y = "Number of episodes") +
    theme(legend.position = "none",
          plot.background = element_rect(fill = "#000000"),
          plot.subtitle = element_text(colour = "#ffffff", size = 13, hjust = 0.5),
          plot.caption = element_text(colour = "#ffffff"),
          panel.background = element_rect(fill = "#edeaf2"),
          axis.text = element_text(colour = "#ffffff", size = 14))
```

```{r}
df %>% 
  select(name, start_date) %>% 
  distinct()
```

```{r}
df %>% 
  separate(col = start_date, into = c("year", "month"), convert = TRUE) -> tidy_year
```

```{r}
tidy_year %>% 
  select(name, year) %>% 
  group_by(year) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = year, y = n))+
  geom_col()+
  geom_text(aes(label = year), check_overlap = T, show.legend = F, size = 3, hjust = 1)+
  coord_flip()+
  theme(legend.position = "none",
          plot.background = element_rect(fill = "#000000"),
          plot.subtitle = element_text(colour = "#ffffff", size = 13, hjust = 0.5),
          plot.caption = element_text(colour = "#ffffff"),
          panel.background = element_rect(fill = "#edeaf2"),
          axis.text = element_text(colour = "#ffffff", size = 14))

```

```{r}
tidy_year %>% 
 mutate() %>% 
 geom_text(aes(hjust = 1) )

```




